name: CI/CD

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  ci:
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-2022, macos-12]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install poetry
        uses: abatilo/actions-poetry@v2
      - uses: actions/setup-python@v5.0.0
        with:
          cache: 'poetry'
      - uses: actions/setup-java@v4.0.0
        with:
          distribution: 'temurin'
          java-version-file: .java-version
      - name: Build and run the project
        run: |
          poetry install
          poetry build
          poetry run pytest
