name: Upload Python Package

on:
  push:
    branches: 
      - main

permissions:
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Python
        uses: actions/setup-python@v4
        # see details (matrix, python-version, python-version-file, etc.)
        # https://github.com/actions/setup-python
      - name: Change folder
        run: |
          cd ./yasik/
          ls
      - name: Install poetry
        uses: abatilo/actions-poetry@v2
     
      - uses: actions/cache@v3
        name: Define a cache for the virtual environment based on the dependencies lock file
        with:
          path: ./.venv
          key: venv-${{ hashFiles('poetry.lock') }}
      - name: Install the project dependencies
        run: |
          cd ./yasik/
          poetry install
      - name: Build the project
        run: |
          cd ./yasik/
          poetry build
      - name: Run the automated tests (for example)
        run: |
          cd ./yasik/
          ls /tests
          poetry run pytest
